name: Lakókocsis nyaralás Görögországban - Korinos.hu
title: Lakókocsis nyaralás Görögországban - Korinos.hu

# Short description (goes below the title; it will also be used in the RSS feed)
description: Lakókocsis nyaralás Görögországban – 3 darab jól felszerelt,légkondicionált lakókocsik várja a pihenni vágyókat. A lakókocsik Korinoson, Paraliatól 5 kilóméterre találhatóak. A kemping széles, homokos tengerparttal rendelkezik. A lakókocsik a parttól 150méterre találhatóak.

# Your name, as you want it to appear underneath each post and in the footer
author: László István

# Your email if you want it to be linked on the contact page
author_email: laszlo1965@gmail.com 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://korinos.hu/

repository: marklaszlo9/jekyll
github_username:  marklaszlo9
# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown]
sass:
  sass_dir: _sass
include:
  - _site
